// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMbc9pMfcXoRR-oKdts8Io7YjPKJcQ6R0',
    appId: '1:287444202435:web:6fb1c97d78bfc5207dc376',
    messagingSenderId: '287444202435',
    projectId: 'todo-app-c5654',
    authDomain: 'todo-app-c5654.firebaseapp.com',
    storageBucket: 'todo-app-c5654.appspot.com',
    measurementId: 'G-VSZP3PL07F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmhFkP8xSQ4cH6ywoIDLv63g7HzpzNut0',
    appId: '1:287444202435:android:82c3fa43d0291a797dc376',
    messagingSenderId: '287444202435',
    projectId: 'todo-app-c5654',
    storageBucket: 'todo-app-c5654.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv51FJPmBEcXJSvx7sfEtBpltDDv486Ns',
    appId: '1:287444202435:ios:7769435567b628897dc376',
    messagingSenderId: '287444202435',
    projectId: 'todo-app-c5654',
    storageBucket: 'todo-app-c5654.appspot.com',
    iosBundleId: 'com.flutter.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv51FJPmBEcXJSvx7sfEtBpltDDv486Ns',
    appId: '1:287444202435:ios:7769435567b628897dc376',
    messagingSenderId: '287444202435',
    projectId: 'todo-app-c5654',
    storageBucket: 'todo-app-c5654.appspot.com',
    iosBundleId: 'com.flutter.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMbc9pMfcXoRR-oKdts8Io7YjPKJcQ6R0',
    appId: '1:287444202435:web:f686112719d3a86c7dc376',
    messagingSenderId: '287444202435',
    projectId: 'todo-app-c5654',
    authDomain: 'todo-app-c5654.firebaseapp.com',
    storageBucket: 'todo-app-c5654.appspot.com',
    measurementId: 'G-WNNQCZ77M3',
  );
}
